### ISSUE TITLE
Site is not responsive 

### ISSUE THREAD

**Issue by PriyansuMaurya** [the-shivam-gupta/the-shivam-gupta.github.io#14]
![image](https://github.com/the-shivam-gupta/the-shivam-gupta.github.io/assets/101447544/3a153e47-71ef-482d-95db-a8c4bcc30092)

**Comment by the-shivam-gupta** [comment]
I will get to it soon as I am currently busy with other tasks.

**Comment by PriyansuMaurya** [comment]
It's lowers the impression when someone visits your portfolio and it's not responsive 😕

**Comment by the-shivam-gupta** [comment]
> It's lowers the impression when someone visits your portfolio and it's not responsive 😕

Please take a moment to review the site.
